version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test: 
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing"
      - run: npm install
      - run: npm test
  hithere:  
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "alo"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires: # cần jobs hithere success thì mới được làm job test, nếu fail thì không được thực hiện test
            - hithere 
        
